project_name: px-darwin
release:
  github:
    owner: metrue
    name: px
  name_template: '{{.Tag}}'
brew:
  github:
    owner: metrue
    name: homebrew-px-daemon
  commit_author:
    name: metrue
    email: h.minghe@gmail.com
  folder: Formula
  install: bin.install "px-daemon"
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  goarm:
  - "6"
  main: ./daemon/daemon.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: px-daemon
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
